language: node_js
node_js:
  - stable
matrix:
  include:
    - if: branch =~ /^(develop)
      env:
        - AWS_REGION="eu-central-1"
        - secure: MZQ2QyE2ahmM6D7k/uBBnv78fMyabCKyk9wZxPXtkQZU6PDE6gZPsuVcq6G6DZyAFZl1JzH1wct3kEatGAPH+TvSCY75+pkKBOereTO/kulrBM/lodFasnW12FosReSNzI5AvBprHRv1PxRbTEGyTyIGy2PekkWCHmxvqY2yDym/yfMLK00+lDZKGTngQzqHbAS5lUoTZb2Iw9WAVzCnEtZfsMj4NG8uzbtYtjgDjuZoJ+HU128jJq9U5ui/WFosajkTOd2xlpr+oJ5hwh+GnqAGBSjEqBjBerdwrH4W9g85C6LdTpsf9JKM4AYOf/hQVzO5yTHRm460QtbdHjxwqzVeFvIe/sg/Uw/sKwmOh3sWObrCxR+nmToXpZaAseLH9Uh1ql2PTv+JT6Nl2ulL9zb1AXsws9sEST3eC7sqAs1yM3GBn2FYmBHDuNHwnD5CDg9RjQlindPjIE7RvbGIGtfnmDk9UfEcvWJcMs+RgkUQqxSGoxpdZuW4vuicbRkWY+p5cf3V3n8v0wU8PXzp3CnZyF3eT5mP/AW2Tckwe+DmdXRkERcP4NpxyCgEpMuxmV6S/3FYG/xOP7ZEWoVQBgN4Os0U4jhzkVFN47r5TKdE8yvDGqaq6dxhNOVqVmtKOsUVbuzLQeDJrpbCQk6zKdygRoqTqWLkFanTURQ36rA=
    - if: branch =~ /^(master)
      env:
        - AWS_REGION="eu-central-1"
        - secure: MZQ2QyE2ahmM6D7k/uBBnv78fMyabCKyk9wZxPXtkQZU6PDE6gZPsuVcq6G6DZyAFZl1JzH1wct3kEatGAPH+TvSCY75+pkKBOereTO/kulrBM/lodFasnW12FosReSNzI5AvBprHRv1PxRbTEGyTyIGy2PekkWCHmxvqY2yDym/yfMLK00+lDZKGTngQzqHbAS5lUoTZb2Iw9WAVzCnEtZfsMj4NG8uzbtYtjgDjuZoJ+HU128jJq9U5ui/WFosajkTOd2xlpr+oJ5hwh+GnqAGBSjEqBjBerdwrH4W9g85C6LdTpsf9JKM4AYOf/hQVzO5yTHRm460QtbdHjxwqzVeFvIe/sg/Uw/sKwmOh3sWObrCxR+nmToXpZaAseLH9Uh1ql2PTv+JT6Nl2ulL9zb1AXsws9sEST3eC7sqAs1yM3GBn2FYmBHDuNHwnD5CDg9RjQlindPjIE7RvbGIGtfnmDk9UfEcvWJcMs+RgkUQqxSGoxpdZuW4vuicbRkWY+p5cf3V3n8v0wU8PXzp3CnZyF3eT5mP/AW2Tckwe+DmdXRkERcP4NpxyCgEpMuxmV6S/3FYG/xOP7ZEWoVQBgN4Os0U4jhzkVFN47r5TKdE8yvDGqaq6dxhNOVqVmtKOsUVbuzLQeDJrpbCQk6zKdygRoqTqWLkFanTURQ36rA=
cache: yarn
script:
  - yarn global add serverless
  - yarn build
  - yarn test:single
  - yarn build-storybook
  - mv storybook-static storybook
  - mv storybook build
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - sls deploy -v -s test
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script:
      - sls deploy -v -s prod
    on:
      branch: master
notifications:
  slack: $SLACK
