version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
      - run:
          command: |
            mkdir /home/circleci/test-results
      - store_test_results:
          path: /home/circleci/test-results
workflows:
    build-and-test:
      jobs:
        - build-and-test