export enum TransactionStatus {
  DEPOSIT_PENDING = 'DEPOSIT_PENDING',
  WITHDRAW_PENDING = 'WITHDRAW_PENDING',
  DEPOSIT_CONFIRMED = 'DEPOSIT_CONFIRMED',
  WITHDRAW_CONFIRMED = 'WITHDRAW_CONFIRMED',
  DEPOSIT_REJECTED = 'DEPOSIT_REJECTED',
  TRANSACTION_REJECTED = 'TRANSACTION_REJECTED',
  WITHDRAW_REJECTED = 'WITHDRAW_REJECTED',
  WITHDRAW_SUBMITTED = 'WITHDRAW_SUBMITTED',
}
