name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    # env:
    #   REACT_APP_BACKEND_URL: wss://dev.jinglebets.com/graphql

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: |
          ~/.npm
          **/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: yarn
      
    - name: Build
      run: yarn build
    
    - name: Test
      run: yarn test:single
      
    - name: AWS Deploy push
      uses: ItsKarma/aws-cli@v1.70.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      with:
        args: >-
          deploy push
          --application-name cc-front
          --description "This is a revision for the cc-front"
          --no-ignore-hidden-files
          --s3-location s3://jinglebets-cc-front/jinglebets-master-cc-front.zip
          --source .

    - name: AWS Create Deploy
      uses: ItsKarma/aws-cli@v1.70.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      with:
        args: >-
          deploy create-deployment
          --application-name cc-front
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name both
          --file-exists-behavior OVERWRITE
          --s3-location bucket=jinglebets-cc-front,key=jinglebets-master-cc-front.zip,bundleType=zip

    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always()

dev-build:
  runs-on: ubuntu-latest
  needs: [test]  
  env:
    REACT_APP_BACKEND_URL: wss://dev.jinglebets.com/graphql

  steps:
  - uses: actions/checkout@v2
    
  - name: Use Node.js
    uses: actions/setup-node@v1
    with:
      node-version: '12.x'

  - name: Cache node modules
    uses: actions/cache@v2
    env:
      cache-name: cache-node-modules
    with:
      path: |
        ~/.npm
        **/node_modules
      key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      restore-keys: |
        ${{ runner.os }}-build-${{ env.cache-name }}-
        ${{ runner.os }}-build-
        ${{ runner.os }}-

  - name: Install dependencies
    run: yarn
    
  - name: Build
    run: yarn build
     
  - name: AWS Deploy push
    uses: ItsKarma/aws-cli@v1.70.0
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    with:
      args: >-
        deploy push
        --application-name cc-front
        --description "This is a revision for the cc-front"
        --no-ignore-hidden-files
        --s3-location s3://jinglebets-cc-front/jinglebets-master-cc-front.zip
        --source .

  - name: AWS Create Deploy
    uses: ItsKarma/aws-cli@v1.70.0
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    with:
      args: >-
        deploy create-deployment
        --application-name cc-front
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name dev
        --file-exists-behavior OVERWRITE
        --s3-location bucket=jinglebets-cc-front,key=jinglebets-master-cc-front.zip,bundleType=zip

  - uses: 8398a7/action-slack@v3
    with:
      status: ${{ job.status }}
      fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
    if: always()

stage-build:
  runs-on: ubuntu-latest
  needs: [test]  
  env:
    REACT_APP_BACKEND_URL: wss://staging.jinglebets.com/graphql

  steps:
  - uses: actions/checkout@v2
    
  - name: Use Node.js
    uses: actions/setup-node@v1
    with:
      node-version: '12.x'

  - name: Cache node modules
    uses: actions/cache@v2
    env:
      cache-name: cache-node-modules
    with:
      path: |
        ~/.npm
        **/node_modules
      key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      restore-keys: |
        ${{ runner.os }}-build-${{ env.cache-name }}-
        ${{ runner.os }}-build-
        ${{ runner.os }}-

  - name: Install dependencies
    run: yarn
    
  - name: Build
    run: yarn build
     
  - name: AWS Deploy push
    uses: ItsKarma/aws-cli@v1.70.0
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    with:
      args: >-
        deploy push
        --application-name cc-front
        --description "This is a revision for the cc-front"
        --no-ignore-hidden-files
        --s3-location s3://jinglebets-cc-front/jinglebets-master-cc-front.zip
        --source .

  - name: AWS Create Deploy
    uses: ItsKarma/aws-cli@v1.70.0
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    with:
      args: >-
        deploy create-deployment
        --application-name cc-front
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name staging
        --file-exists-behavior OVERWRITE
        --s3-location bucket=jinglebets-cc-front,key=jinglebets-master-cc-front.zip,bundleType=zip

  - uses: 8398a7/action-slack@v3
    with:
      status: ${{ job.status }}
      fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
    if: always()    